#!/bin/bash
version="v1.59"
echo "Hello ! #$version# Info at https://git.aevl.net/tek/umupdate #To use run # bash update or bash <(curl -s https://git.aevl.net/tek/umupdate/raw/branch/main/update)"
if [ -f "/bin/update" ]; then
   installed_version=$(grep -oP '(?<=#)\S+(?=#)' /bin/update)
   echo "Installed Version is "$installed_version
   if [ "$installed_version" == "$version" ]; then
       echo "Version matches!"
   else
       echo "Version mismatch! Installed version: $installed_version"
       echo "The file /bin/update already exists."
       read -p "Do you update to a new version? (Y/n): " choice 
       choice="${choice:-y}"
       if [ "$choice" == "y" ]; then
           echo "Removing old"
           sudo rm /bin/update
           echo $USER"@"$HOSTNAME
           sleep 3
           echo "Running new bash"
           #bash <(curl -s https://git.aevl.net/tek/umupdate/raw/branch/main/update)
           echo "Bye! $USER@$HOSTNAME"
           exit;
       else
           echo "Cancelled."
       fi
   fi
else
    echo "The file /bin/update does not exist."
    read -p "Do you want to install it? (y/n): " -e choice
    if [ "$choice" == "y" ]; then
        echo -e "#!/bin/bash \n echo \"$version\" \n echo \"Hello! $USER@$HOSTNAME\" \n echo \"Assistance at https://git.aevl.net/tek/umupdate\" #To use run \n echo \"bash update\" \n bash <(curl -s https://git.aevl.net/tek/umupdate/raw/branch/main/update) \n echo \"$USER bye! XD \"" | sudo tee /bin/update > /dev/null
        sudo chmod 644 /bin/update
        sudo chmod +x /bin/update
        echo "Verifying contents"
        cat /bin/update
        echo "Installed /bin/update successfully."
        sleep 6
    else
        echo "Installation cancelled."
    fi
fi