#!/bin/bash
echo "#V.14# To use this in cli use"
echo "sudo nano /bin/prune
# copy the next 3 lines into it with, and chmod it to 755  
#!/bin/bash
bash <(curl -s https://git.aevl.net/tek/umupdate/raw/branch/main/prune)
echo 'end of prune'
#To use run
bash prune
";echo "Sleeping for 4";sleep 4

echo "$USER pruning @$ip"
echo "Checking for podman"
if command -v podman &>/dev/null; then
    echo "Podman is installed. Proceeding with the commands..."
    echo "Podman List"
    sudo podman ps
    echo "Stop all"
    sudo podman stop --all
    echo "Prune?"
    sudo podman container prune
    sudo podman ps
    echo "Updating"
    sudo podman pull 
    #cloudflare/cloudflared
    echo "bash start"
    echo "starting if device has it on $ip"
    sleep 1
    echo "if next line is an error you need to make the file on the vm, and add the docker container info"
    bash /usr/bin/start
    echo "resuming..."
    echo "Status"
    sudo podman ps
else
    echo "Error: Podman not found. Please install Podman and try again."
fi
