#!/bin/bash
echo "Welcome $USER this is prunes $ip"
echo "Podman List"
sudo podman ps
echo "Stop all"
sudo podman stop --all
echo "Prune?"
sudo podman container prune
sudo podman ps
echo "Updating"
sudo podman pull cloudflare/cloudflared
echo "bash start"
echo "starting if device has it on $ip"
sleep 1
bash /usr/bin/start
echo "resuming..."
echo "Status"
sudo podman ps