#!/bin/bash
echo "#v.08.1# Tailscale update checker, use this in cli/tui to use"
echo "sudo nano /bin/tailscalechk
# copy the next 3 lines into it with, and chmod it to 755  
#!/bin/bash
bash <(curl -s https://git.aevl.net/tek/umupdate/raw/branch/main/tailscalechk)
echo 'bye';
"
echo "#To use run"
echo "bash tailscalechk"
sleep 2
echo "This was made for ArchLinux"
# Get the installed version of tailscale
installed_version=$(sudo pacman -Qi tailscale | awk '/^Version/ {gsub(/-.*$/, "", $3); print $3}')
echo $installed_version
# Get the running version of tailscale
running_version=$(sudo tailscale version | awk '/^([0-9]+\.)+[0-9]+/{sub(/-dev.*/, "", $1); print $1}')
echo $running_version
# Compare the versions using 'sort' command
# '-V' flag performs a version sort (e.g., 1.2 < 1.11)
if [[ "$installed_version" != "$running_version" ]]; then
    echo "Running version is older than installed version. Restarting tailscaled..."
    sudo tailscale version
    sudo systemctl restart tailscaled
    sudo systemctl status  tailscaled
else
    echo "Running version is up to date."
fi
echo "Running verion" 
sudo pacman -Qi tailscale | awk '/^Version/ {gsub(/-.*$/, "", $3); print $3}'
echo "Installed version"
sudo tailscale version | awk '/^([0-9]+\.)+[0-9]+/{sub(/-dev.*/, "", $1); print $1}'
echo "tailscalechk complete ;-p"