#!/bin/bash
echo "#v1# Tailscale update checker, use this in cli/tui to use"
echo "sudo nano /bin/tailscalechk
# copy the next 3 lines into it with, and chmod it to 755  
#!/bin/bash
bash <(curl -s https://git.aevl.net/tek/umupdate/raw/branch/main/tailscalechk)
echo 'bye';
"
echo "#To use run"
echo "bash tailscalechk"
sleep 2
echo "This was made for ArchLinux"

# Function to check if a command executed successfully
check_command() {
    if [ $? -ne 0 ]; then
        echo "Error: $1 failed"
        exit 1
    fi
}

# Get the installed version of tailscale
installed_version=$(sudo pacman -Qi tailscale | awk '/^Version/ {gsub(/-.*$/, "", $3); print $3}')
check_command "pacman -Qi tailscale"

echo "Installed version: $installed_version"

# Get the running version of tailscale
running_version=$(sudo tailscale version | awk '/^([0-9]+\.)+[0-9]+/{sub(/-dev.*/, "", $1); print $1}')
check_command "tailscale version"

echo "Running version: $running_version"

# Compare the versions using 'sort' command
if [[ "$installed_version" != "$running_version" ]]; then
    echo "Running version is older than installed version. Restarting tailscaled..."
    sudo tailscale version
    sudo systemctl restart tailscaled
    sudo systemctl status  tailscaled
else
    echo "Running version is $running_version up to date. Installed version is $installed_version up to date."
    sleep 3
fi

echo "tailscalechk complete ;-p"
sleep 3